# Wine Pairing

### Pre-processing Data

```{r}
library(tidyverse)
```

```{r}
# Reading in the orders.
orders_temp <- read.csv("https://raw.githubusercontent.com/sjsimmo2/DataMining-Fall/master/orderData.csv")

# Viewing the order item types and frequencies.
table(orders_temp$item)

# Creating a unique identifier for each individual ordering. It's the string combination of each individual's order number and seat number.
orders_temp$order_id <- paste(orders_temp$orderNo, "_", orders_temp$seatNo, sep = "")

# Checking to confirm that it worked as intended. If it worked, then there should be three counts of each order identifier, because each person orders three items.
table(orders_temp$order_id) %>% max()
table(orders_temp$order_id) %>% min()

# Because the min and max are the same, all table values are 3. 

# This data set is actually really easy to work with. Each individual orders three items, without exception. Their first item is a meat, their second item is a wine, and their third item is a side. Our job is to determine which wine goes with which meat, so the side dish is irrelevant. We can remove all side dishes from the dataframe.

# Conveniently, the side dishes are every third row in the dataframe. So we just have to remove every third row.

orders <- orders_temp[-seq(3, nrow(orders_temp), 3),]

head(orders)

table(orders$item)

```

```{r}

# Now we have to format the dataframe as a transaction object to run the analysis.
library(arules)

# split() apparently takes all values for item and saves them to a massive list, where each element in the list is the unique identifier, and each element contains a vector of values. In this case, each element is an order_id, and each customer_id contains both the meat order and the wine order.

# as() can turn this list object into a transaction data set. I guess there's literally a transactions data structure in R.

wine_transact <- as(split(orders$item, orders$order_id), "transactions")

# We can use inspect() to see the items of a single transaction combined together.
inspect(wine_transact)

# The transaction object type lets us looks at item labels.
wine_transact@itemInfo
```

```{r}
# This is how we create a set of rules linking items together. Lower support and confidence parameters allow for more linking rules to be shown. If parameter standards are too high, there won't be any linking rules to inspect.
rules <- apriori(wine_transact, parameter = list(supp = 0.001, conf = 0.1, target = "rules"))

# Now we just sort rules by confidence.
rules <- sort(rules, by = "confidence", decreasing = TRUE)


# install.packages("arulesViz"). This used to plot rules.
library(arulesViz)


# Now we can give a plot of support, lift and confidence for each linking rule. I'm pretty sure that those linear dots on the bottom of the graph are some kind of "no link" baseline.
# plot(rules)

# Subsetting the ten rules with the highest confidence.
top10rules <- head(rules, n = 10, by = "confidence")

# Plotting the top 10 rules with a weird interactive html chart.
plot(top10rules, method <- "graph", engine = "htmlwidget")

# Now selecting top links for each meat type.
temp <- data.frame(inspect(rules))

# Selecting the confidence grouped by lhs and rhs.

# Now ordering by ascending rhs name and then descending confidence.
temp <- temp[temp$lhs != "{}",]
temp <- temp[order(temp$lhs, -temp$confidence),] %>% select(lhs, rhs, confidence, support, lift, count)



# Displaying the ordered data. With current parameters, we have a link for every dish except roast chicken, which is the least popular dish.
temp <- temp[temp$lhs %in% c("{Duck Breast}", "{Filet Mignon}", "{Pork Chop}", "{Pork Tenderloin}", "{Salmon}", "{Sea Bass}", "{Swordfish}", "{Roast Chicken}"), ]

temp <- temp %>% mutate(count_above_expectation = (count - count/lift))

temp

```

```{r}
# For the sake of data exploration, let's view every wine/meat combination:
# We create a c-bind of all meats and all wines, and then use %>% table() to see all combinations.
cbind(orders[seq(2,nrow(orders), 2),c("item")], orders[seq(1,nrow(orders), 2),c("item")]) %>% data.frame() %>% rename(wine = X1, meat = X2) %>% table()


```

Checking for bad combinations

```{r}

# Since we're looking for low lift, we want a really low standard for confidence and support in creating riles.
bad_rules <- apriori(wine_transact, parameter = list(supp = 0.000001, conf = 0.00000000015, target = "rules"))

# Sort bad_rules by increasing lift.
bad_rules <- sort(bad_rules, by = "lift", decreasing = FALSE)

# I find that the result's easier to work with when it's a data frame.
temp_bad <- data.frame(inspect(bad_rules))

# Selecting the confidence grouped by lhs and rhs.

# Now ordering by ascending rhs name and then ascending lift.
temp_bad <- temp_bad[temp_bad$lhs != "{}",]
temp_bad <- temp_bad[order(temp_bad$lhs, temp_bad$lift),] %>% select(lhs, rhs, confidence, support, lift, count)


# Displaying the ordered data. We only keep items with meat on the lhs.
temp_bad <- temp_bad[temp_bad$lhs %in% c("{Duck Breast}", "{Filet Mignon}", "{Pork Chop}", "{Pork Tenderloin}", "{Salmon}", "{Sea Bass}", "{Swordfish}", "{Roast Chicken}"), ]

# count_below_expectation to give a sense of scale in evaluating lift.
temp_bad <- temp_bad %>% mutate(count_below_expectation = (count/lift - count))

```

```{r}
# Selecting the worst combination for each meat:

# z is a vector of all the minimum lifts by meat type, and y is a vector of minimum confidence by meat type.
z <- (temp_bad %>% group_by(lhs) %>% summarize(min_lift = min(lift)))$min_lift
y <- (temp_bad %>% group_by(lhs) %>% summarize(min_conf = min(confidence)))$min_conf

# x is a vector of largest amounts below expectation.
x <- (temp_bad %>% group_by(lhs) %>% summarize(shortfall = max(count_below_expectation)))$shortfall

# Displaying wine/meat combinations with the lowest confidence OR the lowest lift.
temp_bad %>% filter( ((lift %in% z) | (confidence %in% y)) & lift <=1) %>% mutate(count_below_expectation = (count/lift - count))

# Displaying wine/meat combinations with the greatest count_below_expectation, where expectation = n*p(wine)*p(meat). This metric helps to give a sense of how big of a drop in wine popularity occurs when a particular meat is purchased. 
temp_bad %>% filter( count_below_expectation %in% x ) %>% mutate(count_below_expectation = (count/lift - count))


```

### Fancy Plots

```{r}
library(ggplot2)

# Reload Data
data <- read.csv('https://raw.githubusercontent.com/sjsimmo2/DataMining-Fall/master/orderData.csv')

# Filter and reshape data by meat
data['type'] <- c('meat', 'wine', 'side')
data1 <- data %>%
  pivot_wider(names_from = type, values_from = item) %>%
  select(meat, wine) %>%
  count(meat)

# Plot 1
font = 'sans'
ggplot(data=data1, aes(reorder(x=meat, -n), y=n)) +
  geom_bar(stat="identity", position = 'dodge', fill="#6d0202") +
  
  # Plot labels and title
  labs(x = "Entrée",
       y = "Orders") +
  
  # Adjust theme
  theme_bw() +
  
  # Labels Size
  theme(axis.text.x = element_text(size = 12,  
                                   family = font,
                                   angle = 45,
                                   hjust = 1,
                                   vjust = 1)) +
  
  theme(axis.text.y = element_text(size = 12,  
                                   family = font)) +
  
  theme(axis.title.x = element_text(size = 22,
                                    family = font)) +
  
  theme(axis.title.y = element_text(size = 22, 
                                    family = font,
                                    vjust = 2.25))

# Filter and reshape data by meat and wine
data2 <- data %>%
  pivot_wider(names_from = type, values_from = item) %>%
  select(meat, wine) %>%
  count(meat, wine) %>%
  # The most popular wine for each meat
  filter(wine %in% c("Blackstone Merlot",
                     "Duckhorn Chardonnay",
                     "Adelsheim Pinot Noir",
                     "Oyster Bay Sauvignon Blanc",
                     "Total Recall Chardonnay"))

# Wine colors
wine_pal <- c("#ee7272", "#6d0202", "#919572", "#ebc19b", "#fff1cf")

# plot 2
ggplot(data=data2, aes(reorder(x=meat, -n), y=n, fill=wine)) +
  geom_bar(stat="identity", position = 'dodge') +
  
  # Plot labels and title
  labs(x = "Entrée",
       y = "Orders") +
  
  # Wine Colors
  scale_fill_manual(values=wine_pal,
                    name='Most Popular Wine') +
  
  # Adjust theme
  theme_bw() +
  
  # Box the Legend
  theme(legend.box.background = element_rect(color="black", linewidth = 1)) +
  theme(legend.text = element_text(family = font)) +
  
  # Labels Size
  theme(axis.text.x = element_text(size = 12,  
                                   family = font,
                                   angle = 45,
                                   hjust = 1,
                                   vjust = 1)) +
  
  theme(axis.text.y = element_text(size = 12,  
                                   family = font)) +
  
  theme(axis.title.x = element_text(size = 22,
                                    family = font)) +
  
  theme(axis.title.y = element_text(size = 22, 
                                    family = font,
                                    vjust = 2.25))
```

```{r}
# Affects of side dish on wine selection

# column for pivoting
data['type'] <- c('meat', 'wine', 'side')
# Id column
data$id <- as.integer(paste(data$orderNo, data$seatNo, sep = ''))
# label starch sides
starch <- c('Bean Trio', 'Roasted Potatoes', 'Mashed Potatoes')

# Format data to combine meat and side
data <- data %>%
  pivot_wider(names_from = type, values_from = item) %>%
  mutate(side_type = ifelse(side %in% starch, 'starch', 'veg')) %>%
  mutate(meat_side = paste(meat, side_type, sep = " "))

# Format transaction data
data <- data %>%
  select(id, meat_side, wine) %>%
  pivot_longer(c(meat_side, wine))

# Association testing
trans.dat <- as(split(data$value, data$id), "transactions")

rules <- apriori(trans.dat, 
                 parameter = list(supp = 0.01, 
                                  conf = 0.1, 
                                  target="rules"))
rules <- sort(rules, by="confidence", decreasing=TRUE)

inspect(rules)
```
